parameters:
#    wanaplay_booker.example.class: Wanaplay\Bundle\BookerBundle\Example

services:
    wanaplay_booker.service:
        class: Wanaplay\Bundle\BookerBundle\Services\BookerService
        calls:
            - [ setLogger, [ @logger ]]
        tags:
            - { name: monolog.logger, channel: wanaplay_bot }