parameters:
services:
    wanaplay_booker.service:
        class: Wanaplay\Bundle\BookerBundle\Services\BookerService
        arguments:
            - %wanaplay_settings_username%
            - %wanaplay_settings_password%
        calls:
            - [ setLogger, [ @logger ]]
        tags:
            - { name: monolog.logger, channel: wanaplay_bot }